config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'homes#top'
  root to: "homes#top"
  get "home/about"=>"homes#about", as: 'about'


  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do

    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "search", to: "users#search"
  end

  get "search" => "searches#search"

  #1対1のチャット機能
  #get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only:[:show, :create]
  #グループ機能の作成
  resources :groups, only: [:index, :show, :create, :update, :new, :edit] do
    resource :group_users, only: [:create, :destroy]
    resources :event_notices, only: [:new, :create]
    get "event_notices" => "event_notices#sent"
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  #1対1のチャット機能
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :rooms, through: :user_rooms
  #閲覧数を表示
  has_many :view_counts, dependent: :destroy

  #グループ機能の作成
  has_many :group_users, dependent: :destroy


  #自分がフォローされる(被フォロー)側の関係性
  has_many :reverse_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  #被フォロー関係を通じて参照→自分がフォローしている人
  has_many :followers, through: :reverse_relationships, source: :follower

  #自分がフォローする側(与フォロー)の関係性
  has_many :relationships, class_name:  "Relationship", foreign_key: "follower_id", dependent: :destroy
  #与フォローの関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed


  #フォローした時の処理
  def follow(user_id)
    relationships.create(followed_id:user_id)
  end
  #フォロー外す時の処理
  def unfollow(user_id)
    relationships.find_by(followed_id:user_id).destroy
  end
  #フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  #検索方法分岐
  def self.looks(search, word)
    if search == "perfect"
      User.where("name LIKE?", "#{word}")
    elsif search == "forward"
      User.where("name LIKE?", "#{word}%")
    elsif search == "backward"
      User.where("name LIKE?", "%#{word}")
    else
      User.where("name LIKE?", "%#{word}%")
    end
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50}




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    #投稿数を数えるモデルを代入
    #今日・前日
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    #今週・先週
    @this_week_book = @books.created_this_week
    @before_week_book = @books.created_before_week
  end

  #指定した日の投稿数を検索
  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
      render 'search_book'
    end
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    redirect_to (user_path(current_user)) unless @user == current_user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_count_books.html.erb
<div class = "table_width">
  <table class = "table table-bordered">
    <thred>
      <tr>
        <th>今日の投稿数</th>
        <th>前日の投稿数</th>
        <th>前日比</th>
      </tr>
    </thred>
    <tbody>
      <tr>
        <td><%= @today_book.count %></td>
        <td><%= @yesterday_book.count %></td>
        <td>
          <% if @yesterday_book.count == 0 %>
           前日の投稿はありません
          <% else %>
          <% @the_day_before = @today_book.count / @yesterday_book.count.to_f %>
          <%= (@the_day_before * 100).round %>
          <% end %>
        </td>
      </tr>
    </tbody>
    <thred>
      <tr>
        <th>今週の投稿数</th>
        <th>先週の投稿数</th>
        <th>前週比</th>
      </tr>
    </thred>
    <tbody>
      <tr>
        <td><%= @this_week_book.count %></td>
        <td><%= @before_week_book.count %></td>
        <td>
          <% if @before_week_book.count == 0 %>
           前週の投稿はありません
          <% else %>
          <% @the_week_before = @this_week_book.count / @before_week_book.count.to_f %>
          <%= (@the_week_before * 100).round %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/users/_count_graph.html.erb
<canvas id="myLineChart"></canvas>
  <script>
    $(document).on('turbolinks:load', function() {
      var ctx = document.getElementById("myLineChart");
      var myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
          datasets: [
            {
              label: '投稿した本の数',
              data: [
                <%= books.created_days_ago(6).count %>,
                <%= books.created_days_ago(5).count %>,
                <%= books.created_days_ago(4).count %>,
                <%= books.created_days_ago(3).count %>,
                <%= books.created_days_ago(2).count %>,
                <%= books.created_days_ago(1).count %>,
                <%= books.created_days_ago(0).count %>
              ],
              borderColor: "rgba(0,0,255,1)",
              backgroundColor: "rgba(0,0,0,0)",
              tension: 0.4
            }
          ],
        },
        options: {
          title: {
            display: true,
            text: '7日間の投稿数の比較'
          },
          responsive: true,
          scales: {
            y:{
              suggestedMin: 0,
              suggestedMax: 10
            },
            x:{
              stacked: true
            },
          },
        }
      });
    });
  </script>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>

        <td><%= render "relationships/btn", user: user %></td>

        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>

  <tr>
   <th>follws</th>
   <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
   <th>followers</th>
   <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<div class='row'>
  <% if current_user != user %>
   <td><%= render "relationships/btn", user: user %></td>
  <% else %>
   <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
     <i class="fas fa-user-cog"></i>
   <% end %>
  <% end %>

  <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
   <%= link_to 'chatを始める', chat_path(user.id), class: "ml-3" %>
  <% end %>
</div>

app/views/users/_search.html.erb
<h4>検索結果</h4>
  <table class='table table-bordered'>
    <thead>
      <tr>
        <th>投稿数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= search_book %></td>
      </tr>
    </tbody>
  </table>

app/views/users/_week_count_books.html.erb
<h4>7日間分の投稿数</h4>
<table class = "table">
  <thred>
    <tr>
      <th>6日前</th>
      <th>5日前</th>
      <th>4日前</th>
      <th>3日前</th>
      <th>2日前</th>
      <th>昨日</th>
      <th>今日</th>
    </tr>
  </thred>
  <tbody>
    <tr>
      <th><%= books.created_days_ago(6).count %></th>
      <th><%= books.created_days_ago(5).count %></th>
      <th><%= books.created_days_ago(4).count %></th>
      <th><%= books.created_days_ago(3).count %></th>
      <th><%= books.created_days_ago(2).count %></th>
      <th><%= books.created_days_ago(1).count %></th>
      <th><%= books.created_days_ago(0).count %></th>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
<div class='row'>

<div class='col-md-3'>
<h2>User info</h2>
<%= render 'info', user: current_user %>

<h2 class="mt-3">New book</h2>
<%= render 'books/form', book: @book %>
</div>

<div class='col-md-8 offset-md-1'>
<h2>Users</h2>
<div>
  <%= link_to "グループを作成する", new_group_path %> |
  <%= link_to "グループ一覧", groups_path %>
</div>
<%= render 'index',users: @users %>
</div>
</div>
</div>

app/views/users/search_book.js.erb
$("#search_result").html("<%= j(render 'search', search_book: @search_book) %>")

app/views/users/show.html.erb
<script src="https://kit.fontawesome.com/b4084b3cf0.js" crossorigin="anonymous"></script>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <%= render 'count_books',books: @books %>
      <%= render 'week_count_books', books: @books %>
      <%= render 'count_graph', books: @books %>

      <%= form_with url: user_search_path(@user), method: :get, data: {remote:true} do |f| %>
       <%= f.date_field :created_at %>
       <%= f.submit '検索', class: 'btn btn-primary'  %>
      <% end %>

      <div id="search_result">
       <% if @search_book.present? %>
        <%= render 'search', search_book: @search_book %>
       <% end %>
      </div>



    </div>
  </div>
</div>