config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'homes#top'
  root to: "homes#top"
  get "home/about"=>"homes#about", as: 'about'


  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do

    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "search", to: "users#search"
  end

  get "search" => "searches#search"

  #1対1のチャット機能
  #get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only:[:show, :create]
  #グループ機能の作成
  resources :groups, only: [:index, :show, :create, :update, :new, :edit] do
    resource :group_users, only: [:create, :destroy]
    resources :event_notices, only: [:new, :create]
    get "event_notices" => "event_notices#sent"
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  #いいね1week多い順にする
  has_many :favorited_users, through: :favorites, source: :user
  has_many :book_comments, dependent: :destroy
  #閲覧数を表示
  has_many :view_counts, dependent: :destroy
  #投稿の時にカテゴリタグを追加する
  has_many :book_tags, dependent: :destroy
  has_many :tags, through: :book_tags



  #検索方法分岐
  def self.looks(search, word)
    if search == "perfect"
      Book.where("title LIKE?", "#{word}")
    elsif search == "forward"
      Book.where("title LIKE?", "#{word}%")
    elsif search == "backward"
      Book.where("title LIKE?", "%#{word}")
    else
      Book.where("title LIKE?", "%#{word}%")
    end
  end

  #本の投稿数を数える(今日.前日)
  scope :created_today, -> {where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> {where(created_at: 1.day.ago.all_day) }
  #本の投稿数を数える(今週.先週)
  scope :created_this_week, -> {where(created_at: Time.now.all_week(:saturday)) }
  scope :created_before_week, ->{where(created_at: 1.week.ago.all_week)}

  #7日分の投稿データ取得
  scope :created_days_ago, ->(n) {where(created_at: n.days.ago.all_day)}
  #7日分の投稿を取り出す
  #def self.before_week_count
    #(1..6).map {|n| created_days_ago(n).count}.reverse
  #end

  #投稿にタグをつける(更新機能)
  def save_tags(savebook_tags)
    #現在のユーザーの持っているskillを引っ張ってきている
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    #今bookが持っているタグと今回保存されたものの差をすでにあるタグとする。古いタグは消す。
    old_tags = current_tags - savebook_tags
    #今回保存されたものと現在の差を新しいタグとする。新しいタグは保存。
    new_tags = savebook_tags - current_tags

    #Destroy old taggings:
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

    #Create new taggings:
    new_tags.each do |new_name|
      book_tag = Tag.find_or_create_by(name:new_name)
      #配列に保存
      self.tags << book_tag
    end
  end

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    #@book = Book.new
    @book = Book.find(params[:id])
    #閲覧数を表示
    unless ViewCount.find_by(user_id: current_user.id, book_id: @book.id)
      current_user.view_counts.create(book_id: @book.id)
    end
    @book_comment = BookComment.new
  end

  def index
  to  = Time.current.at_end_of_day
  from  = (to - 6.day).at_beginning_of_day
  @books = Book.includes(:favorited_users).
   sort {|a,b|
    b.favorited_users.includes(:favorites).where(created_at: from...to).size <=>
    a.favorited_users.includes(:favorites).where(created_at: from...to).size
   }
  @book = Book.new
  @book.user_id = current_user.id
  @books = Book.all.order(params[:sort])
  #閲覧数を表示
    #@book_detail = Book.find(params[:id])
    #unless ViewCount.find_by(user_id: current_user.id, book_id: @book_detail.id)
      #current_user.view_counts.create(book_id: @book_detail.id)
    #end
  end


  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    #投稿にタグを追加
    tag_list = params[:book][:tag_name].split(',')
    if @book.save
      @book.save_tags(tag_list)
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :index
    end
  end


  def edit
    #@book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    #@book = Book.find(params[:id])
    @book.update(book_params)
    if @book.save
       flash[:notice] = "You have updated book successfully."
       redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    #@book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :rate)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book, local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>

  <div class = "form-group">
    <%= f.label "Tag" %>
    <%= f.text_field :tag_name, class: 'form-control book_tag_name' %>
  </div>


  <% if book.id === nil %>
   <div class = "form-group" id = "star">
     <%= f.label :rate %>
     <%= f.hidden_field :rate, id: :review_star, class:'form-control' %>
   </div>

   <script>
     $(document).on('turbolinks:load', function() {
       $('#star').empty();
       $('#star').raty({
         size : 36,
         starOff:   '<%= asset_path('star-off.png') %>',
         starOn:    '<%= asset_path('star-on.png') %>',
         starHalf:  '<%= asset_path('star-half.png') %>',
         scoreName: 'book[rate]',
         half:      true,
       });
     })
   </script>
  <% else %>
   <%= render "static_rate", book: book %>
  <% end %>

  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>

<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>

        <%# 投稿にタグをつけるのリンク %>
        <td>
         <% book.tags.each do |tag| %>
          <%= link_to tag.name, search_path(word: tag.name, range: "tag", serach: "perfect") %>
         <% end %>
        </td>

        <td class =<%= "favorite-" + book.id.to_s %> >
          <%= render "favorites/btn", book: book %>
        </td>

        <td>コメント数：<%= book.book_comments.count %></td>
        <td>
          <p class = "view_count">閲覧数：<%= book.view_counts.count %></p>
        </td>
        <td><%= render "books/static_rate", book: book %></td>
       </tr>

    <% end %>
  </tbody>
</table>

app/views/books/_static_rate.html.erb
<div id = "rate_<%= book.id %>" class = "form-group"></div>
<script>
  $(document).on('turbolinks:load', function() {
    $('#rate_<%= book.id %>').empty();
    $('#rate_<%= book.id %>').raty({
      size: 20,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn:   '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      half:     true,
      readOnly: true,
      score:    <%= book.rate %>,
    });
  });
</script>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= render 'layouts/errors', obj: @book %>
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<script src="https://kit.fontawesome.com/b4084b3cf0.js" crossorigin="anonymous"></script>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
<%= render 'layouts/errors', obj: @book %>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>

    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= link_to '新しい順', books_path(sort: 'created_at DESC') %>
      |
      <%= link_to '評価の高い順', books_path(sort: 'rate DESC') %>
      <%= render 'index', books: @books %>



    </div>
  </div>
</div>

app/views/books/show.html.erb
<script src="https://kit.fontawesome.com/b4084b3cf0.js" crossorigin="anonymous"></script>
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user:@book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to user_path(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <%# 投稿にタグをつけるのリンク %>
          <td>
            <% @book.tags.each do |tag| %>
             <%= link_to tag.name, search_path(word: tag.name, range: "tag", search: "perfect" ) %>
            <% end %>
          </td>

          <td class = <%= "favorite-" + @book.id.to_s %> >
            <%= render "favorites/btn", book: @book %>
          </td>
          <td class = "book-comments-counter">
            <%= render "book_comments/counter", book: @book %>
          </td>
          <td>
            <p class = "view_count">閲覧数：<%= @book.view_counts.count %></p>
          </td>
          <td><%= render "static_rate", book: @book %></td>

          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
          </tr>
          </table>

          <div class = "book-comments-index">
           <%= render "book_comments/index", book: @book %>
          </div>
          <%= render "book_comments/form", book: @book, book_comment: @book_comment %>

    </div>
  </div>
</div>